# Generated by Django 4.2.3 on 2023-07-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=80)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('thumbnail', models.ImageField(blank=True, upload_to='restaurants')),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='restaurants')),
                ('opening_hours', models.TimeField()),
                ('closing_hours', models.TimeField()),
            ],
        ),
    ]
